// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDObXhqJDMViVqB6P8Fbh6IqrD2BbhqucE',
    appId: '1:28049305285:web:c9996c1967e8ab11a78aac',
    messagingSenderId: '28049305285',
    projectId: 'vision-system-bc8ba',
    authDomain: 'vision-system-bc8ba.firebaseapp.com',
    storageBucket: 'vision-system-bc8ba.firebasestorage.app',
    measurementId: 'G-CG5K3T2D1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfi9_A3H5qJErVIsRJe8SYavor0-KAdvs',
    appId: '1:28049305285:android:ac9bb925aa2ff86ba78aac',
    messagingSenderId: '28049305285',
    projectId: 'vision-system-bc8ba',
    storageBucket: 'vision-system-bc8ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAr3VQjlvYP-n0KW_uYBoGE3uGVstyRtw',
    appId: '1:28049305285:ios:5ad44249046813fda78aac',
    messagingSenderId: '28049305285',
    projectId: 'vision-system-bc8ba',
    storageBucket: 'vision-system-bc8ba.firebasestorage.app',
    iosBundleId: 'com.fulers.vision',
  );
}
